// Barrel re-export — backward compatibility
export {Repositories}  from './Repositories.jsx'
export {Environments}  from './Environments.jsx'
export {DevSpace}      from './DevSpace.jsx'
export {Documentation} from './Documentation.jsx'
export {Communication} from './Communication.jsx'
export {Statistics}    from './Statistics.jsx'
export {UsersPage}     from './UsersPage.jsx'
export {SettingsPage}  from './SettingsPage.jsx'
export {HelpPage}      from './HelpPage.jsx'
export {LogoutPage}    from './LogoutPage.jsx'
