name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:

  deploy-test:
    runs-on: [self-hosted, test-server]
    steps:
      - name: Deploy code sur TEST
        run: |
          cd /srv/test/app
          git fetch origin
          git reset --hard origin/staging
          cd /srv/test
          docker compose up -d --build
          sleep 10
          docker ps
          echo "Application visible sur http://192.168.137.57:8080"

  validation-agent:
    needs: deploy-test
    runs-on: [self-hosted, test-server]
    environment:
      name: agent-approval
    steps:
      - name: Validation agent
        run: echo "Agent a approuve"

  validation-chef:
    needs: validation-agent
    runs-on: [self-hosted, test-server]
    environment:
      name: production-approval
    steps:
      - name: Validation chef
        run: echo "Chef a approuve"

  extract:
    needs: validation-chef
    runs-on: [self-hosted, test-server]
    steps:
      - name: Creer archive
        run: |
          mkdir -p /srv/test/archives
          rm -f /srv/test/archives/projet.tar.gz
          tar -czf /srv/test/archives/projet.tar.gz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='storage/logs' \
            --exclude='storage/framework/cache' \
            -C /srv/test/app \
            frontend backend database
          ls -lh /srv/test/archives/projet.tar.gz
          echo "Archive vita"

  deploy-prod:
    needs: extract
    runs-on: [self-hosted, test-server]
    steps:
      - name: Envoyer archive any PROD
        run: |
          scp /srv/test/archives/projet.tar.gz deployer@192.168.137.96:/srv/prod/
          echo "Archive envoyee any PROD"

      - name: Deploy any PROD
        run: |
          ssh deployer@192.168.137.96 "
            mkdir -p /srv/prod/app/frontend &&
            mkdir -p /srv/prod/app/backend &&
            mkdir -p /srv/prod/app/database &&
            tar -xzf /srv/prod/projet.tar.gz -C /srv/prod/app/ &&
            cd /srv/prod &&
            docker compose -f docker-compose.prod.yml down --remove-orphans &&
            docker compose -f docker-compose.prod.yml up -d --build &&
            sleep 10 &&
            docker ps &&
            echo PROD deploye sur http://192.168.137.96:80
          "

  cleanup-test:
    needs: deploy-prod
    runs-on: [self-hosted, test-server]
    steps:
      - name: Cleanup TEST
        run: |
          cd /srv/test
          docker compose down
          echo "TEST arrete - application sur PROD uniquement"