deploy-test:
    runs-on: [self-hosted, test-server]
    environment: staging
    steps:
      - name: Deployer sur TEST
        run: |
          cd /srv/test
          docker compose down
          docker compose up -d --build
          echo "Application visible sur http://192.168.137.68:8080"

  deploy-prod:
    needs: validation-chef
    runs-on: [self-hosted, prod-server]
    steps:
      - name: Deployer sur PROD
        run: |
          cd /srv/prod
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d --build
          echo "Application visible sur http://192.168.137.153"