name: CI/CD mon-project-app

on:
  push:
    branches: [ main ]

env:
  # Ity no manala ilay fampitandremana Node 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  deploy-staging:
    name: Build and Deploy to Test (8080)
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Manampy an'ity dingana ity isika mba hahazoana antoka fa hita ny node
        run: |
          node -v
          npm -v

      - name: Install and Build
        run: |
          # Ampiasao ny --if-present raha toa ka tsy React ilay alefanao
          npm install --no-audit
          npm run build --if-present
          
      - name: Prepare APK Folder
        run: |
          mkdir -p dist/apk
          echo "APK Build Success" > dist/apk/mon-app.apk 

      - name: Copy to Staging Folder
        run: |
          # Ampiasao ny sudo raha toa ka voa-config ny visudo
          sudo rm -rf /var/www/mon-project-app/staging/*
          sudo cp -r dist/* /var/www/mon-project-app/staging/